### ISSUE TITLE
Totally broken.

### ISSUE THREAD

**Issue by roke-julian-lockhart** [writeas/Read.as#10] opened 2023-02-15 20:14 UTC
read.as > certificate expired page > 404
![Screenshot_20230215_201244](https://user-images.githubusercontent.com/42837531/219142539-8c687e0c-ca9a-4081-ba8d-2b9811262d7a.png)

**Comment by thebaer** [comment] 2023-02-16 16:47
This seems to be the demo site, not a bug in the application, so I'll close this.

**Closed as completed by thebaer** 2023-02-16 16:47 UTC

**Comment by roke-julian-lockhart** [comment] 2023-02-16 21:28
@thebaer, where should this be reported to, then?

**Comment by thebaer** [comment] 2023-02-17 21:44
Email is best, but I've seen it now. No plans to revive this site for now, as this project is on hold.
